version: 1
disable_existing_loggers: true

formatters:
  brief:
    format: '%(message)s'
  precise:
    format: '%(asctime)s [%(levelname)-5.5s] %(name)-15s :c%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    level: DEBUG
    filename: digitalfarm.log
    maxBytes: 10485760 # 10 MB
    backupCount: 20
    encoding: utf8
  email:
    class: logging.handlers.SMTPHandler
    mailhost: localhost
    fromaddr: my_app@domain.tld
    toaddrs:
      - support_team@domain.tld
      - dev_team@domain.tld
    subject: Houston, we have a problem.
root:
    level: NOTSET
    handlers: [console, file]
    propagate: yes
